# Cloud Build configuration for Arth-Sutradhar
# Usage:
#   gcloud builds submit . --config=cloudbuild.yaml --project=arth-sutradhar --substitutions=_TAG=latest
steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-f"
      - "frontend/api/Dockerfile"
      - "-t"
      - "asia-south1-docker.pkg.dev/$PROJECT_ID/arth-sutradhar/arth-sutradhar-api:${_TAG}"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "asia-south1-docker.pkg.dev/$PROJECT_ID/arth-sutradhar/arth-sutradhar-api:${_TAG}"

images:
  - "asia-south1-docker.pkg.dev/$PROJECT_ID/arth-sutradhar/arth-sutradhar-api:${_TAG}"

substitutions:
  _TAG: latest
